name: test_superhero
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  injectable: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  auto_route: 7.8.4
  flutter_gen_runner: ^5.5.0+1
  flutter_localization: ^0.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flash: ^3.1.1
  gap: ^3.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  generate: true 

  assets: 
    - assets/images/

  
